name: Lint assets

on:
  push:
    paths:
      - '**.js'
      - '**.md'
      - '**.scss'
  pull_request:
    paths:
      - '**.js'
      - '**.md'
      - '**.scss'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm ci

    - name: Lint assets
      run: npm run lint
